---
language: python

python:
  - "3.6"

before_install:
  # download and install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda create -n test_env python=$TRAVIS_PYTHON_VERSION pip cmake
  - source activate test_env

install:
  # install the most recent rdkit package from the RDKit anaconda channel.
  - conda install -q -c rdkit rdkit

  - pip install -e .[dev]

script:
  # Style guide enforcement
  - flake8
  - |
    yapf --quiet --style "{based_on_style: pep8, blank_line_before_nested_class_or_def: true, indent_dictionary_value: true, dedent_closing_brackets: true, column_limit: 99}" --recursive .
  # static typing
  - mypy .
  # Test suite
  - pytest
