---
language: python

python:
  - "3.6"

install:
  - pip install -e .[dev]
  # install RDKit. This is not as a setup dependency in order not to install it
  # in downstream packages and avoid potential conflicts with the conda
  # installation of RDKit
  - pip install rdkit-pypi==2021.3.2

script:
  # Style guide enforcement
  - flake8
  - yapf --quiet --recursive .
  # static typing
  - mypy .
  # Test suite
  - pytest
