# LICENSED INTERNAL CODE. PROPERTY OF IBM.
# IBM Research Zurich Licensed Internal Code
# (C) Copyright IBM Corp. 2021
# ALL RIGHTS RESERVED

name: rxn_chemutils
channels:
  - https://conda.anaconda.org/rdkit
dependencies:
  - rdkit=2020.03.1
  - python>=3.6,<3.8
  - pip>=19.1
  - pip:
    - attrs==19.1.0
    - click==7.0
    - loguru==0.5.3
    - rxn_utilities @ git+https://${GHE_TOKEN}@github.ibm.com/rxn/rxn_utilities@latest
    - -e .
    # test requirements
    - flake8==3.8.4
    - mypy==0.761
    - pytest==5.3.4
    - yapf==0.30.0
